In [1]:
%pylab inline
import random

Populating the interactive namespace from numpy and matplotlib


## Random Number generator
A pseudo-random number generator is an object that outputs a value each time it is called.

the object has a **state** which is initialized using the `seed` command and is updated each time the generator is called.  

The output value is a function of the seed.

In [2]:
random.seed(22)
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
state=random.getstate()
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")

0, 0, 0, 1, 0, 0, 1, 0, 

In [3]:
random.setstate(state)
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")
print(random.randrange(2),end=", ")

0, 0, 1, 0, 

The binary sequence is determined by the initial state.

Why do we say that the generated is **PseudoRandom**?

Because it looks random to most tests

In [ ]:
random.random?

In [4]:
def generate(n=10):
    seq=[(random.random()>0.5)*2-1 for i in range(n)]
    return array(seq)

In [5]:
random.seed(23)
n=100000
R=generate(n)
R[:10]

array([ 1,  1,  1, -1,  1, -1,  1, -1, -1, -1])

### Pseudo Random number generators pass most tests
 * An ideal random number generator will provide the same distribution of outcomes as a true random generator for every test.

In [58]:
# mean
sum(R)/n

0.00116

In [10]:
I=ones(n)
I[:int(n/2)]=-1  # mean after flip sign of first part 
I

array([-1., -1., -1., ...,  1.,  1.,  1.])

In [11]:
sum(R*I)/n

0.00428

In [12]:
I=ones(n)
I[0:n:2]=-1    # mean after flip sign even locations
I

array([-1.,  1., -1., ...,  1., -1.,  1.])

In [13]:
sum(R*I)/n

0.00308

### It is impossible to construct a PRNG that passes all tests
* If the tester with unlimited computational power, it can run a separate test for each possible seed and identify the seed that conforms with the sequence.

### In practice, `python.random` is good enough
* But not always, for cryptographic/Key-Chain applications, the recommendation is to use the stronger `secrets` module.
* Or a [hardware random number generator](https://en.wikipedia.org/wiki/Hardware_random_number_generator) 

### Hash Function
* A **random mapping** is a function $R:\{1,\ldots,n\} \to \{1,\ldots,m\}$ such that for 
each $1 \leq i \leq n$ the value $R(i)$ is distributed uniformly over $\{1,\ldots,m\}$
* A **Hash function family** $H_j$ is a collection of functions $H_j:\{1,\ldots,n\} \to \{1,\ldots,m\}$ such that if $j$ is chosen at random then $H_j(i)$ is indistinguishable from a random mapping. (Assuming the adversary has restricted rsources).

### Homework
Use the functions in the module `random` to construct a hash function.